### ISSUE TITLE
[bug] 安装好插件以后无法进入页面

### ISSUE THREAD

**Issue by Brianwind** [emako/SG.Plugin.Model.Viewer#1]
将dll文件放入plugin文件夹以后，主界面能出现插件选项，但是点击以后无反应，无法进入该插件的页面。
![image](https://user-images.githubusercontent.com/49585907/155470340-1690cd36-e95f-411e-a1d6-ac39a392b665.png)

**Comment by emako** [comment]
因为SG本体改动了
已发行：[1.0.0.2](https://github.com/emako/SG.Plugin.Drop.Wish/releases/tag/1.0.0.2)
